name: plottertopicos
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.1.0
  cupertino_icons: ^0.1.2
  positioned_tap_detector: ^1.0.3
  jaguar_serializer: 
  path_provider: ^2.0.1
  file_picker: ^3.0.0
  flutter_colorpicker: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  jaguar_serializer_cli:


flutter:


  uses-material-design: true
